name: e_baladya
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.7.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  file_picker: ^10.3.8
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  url_launcher: ^6.3.2
  firebase_messaging: ^16.1.0
  http: ^1.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mocktail: ^1.0.4
  test: ^1.25.2
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_blue.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
